//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationPlanner.Implementation {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacationPlanner.Implementation.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для вас создан отпуск №{0}..
        /// </summary>
        internal static string CreatedVacationMessage {
            get {
                return ResourceManager.GetString("CreatedVacationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша заявка на отпуск №{0} успешно создана..
        /// </summary>
        internal static string CreatedVacationRequestMessage {
            get {
                return ResourceManager.GetString("CreatedVacationRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша заявка №{0} полностью согласована..
        /// </summary>
        internal static string RequestApprovedByHrMessage {
            get {
                return ResourceManager.GetString("RequestApprovedByHrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша заявка №{0} прошла первый этап согласования..
        /// </summary>
        internal static string RequestApprovedByManagerMessage {
            get {
                return ResourceManager.GetString("RequestApprovedByManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша заявка №{0} была отклонена HR..
        /// </summary>
        internal static string RequestRejectedByHrMessage {
            get {
                return ResourceManager.GetString("RequestRejectedByHrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша заявка №{0} была отклонена руководителем..
        /// </summary>
        internal static string RequestRejectedByManagerMessage {
            get {
                return ResourceManager.GetString("RequestRejectedByManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш код восстановления пароля: {0}.
        /// </summary>
        internal static string RestorePasswordMessage {
            get {
                return ResourceManager.GetString("RestorePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте, {0}! Ваш пароль был успешно изменен..
        /// </summary>
        internal static string SuccessChangePasswordMessage {
            get {
                return ResourceManager.GetString("SuccessChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте, {0}! Вы успешно зарегистрированы..
        /// </summary>
        internal static string SuccessRegistrationMessage {
            get {
                return ResourceManager.GetString("SuccessRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для сотрудника создан отпуск №{0}..
        /// </summary>
        internal static string VacationCreatedForManagerMessage {
            get {
                return ResourceManager.GetString("VacationCreatedForManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник отправил заявку №{0} на согласование..
        /// </summary>
        internal static string VacationRequestSubmittedMessage {
            get {
                return ResourceManager.GetString("VacationRequestSubmittedMessage", resourceCulture);
            }
        }
    }
}
