//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationPlanner.Implementation {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Subjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subjects() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacationPlanner.Implementation.Subjects", typeof(Subjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение пароля.
        /// </summary>
        internal static string ChangePasswordSubject {
            get {
                return ResourceManager.GetString("ChangePasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация в VacationPlanner.
        /// </summary>
        internal static string RegistrationSubject {
            get {
                return ResourceManager.GetString("RegistrationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля.
        /// </summary>
        internal static string RestorePasswordSubject {
            get {
                return ResourceManager.GetString("RestorePasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создан отпуск сотруднику.
        /// </summary>
        internal static string SubjectCreatedVacationForManager {
            get {
                return ResourceManager.GetString("SubjectCreatedVacationForManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая заявка на согласование.
        /// </summary>
        internal static string SubjectCreatedVacationRequest {
            get {
                return ResourceManager.GetString("SubjectCreatedVacationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создан отпуск.
        /// </summary>
        internal static string SubjectVacationCreated {
            get {
                return ResourceManager.GetString("SubjectVacationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка отклонена HR.
        /// </summary>
        internal static string SubjectVacationRejectedByHr {
            get {
                return ResourceManager.GetString("SubjectVacationRejectedByHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка отклонена руководителем.
        /// </summary>
        internal static string SubjectVacationRejectedByManager {
            get {
                return ResourceManager.GetString("SubjectVacationRejectedByManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отпуск согласован.
        /// </summary>
        internal static string SubjectVacationRequestApprovedByHr {
            get {
                return ResourceManager.GetString("SubjectVacationRequestApprovedByHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка согласована руководителем.
        /// </summary>
        internal static string SubjectVacationRequestApprovedByManager {
            get {
                return ResourceManager.GetString("SubjectVacationRequestApprovedByManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создана заявка на отпуск.
        /// </summary>
        internal static string SubjectVacationRequestCreated {
            get {
                return ResourceManager.GetString("SubjectVacationRequestCreated", resourceCulture);
            }
        }
    }
}
